import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link, useNavigate } from 'react-router-dom';
import { ShoppingCartIcon, UserCircleIcon } from '@heroicons/react/24/outline';
import { useAuthStore } from '@/context/store';
import { useCartStore } from '@/context/store';
export default function Navbar({ onLogout }) {
    const navigate = useNavigate();
    const { user } = useAuthStore();
    const cartItems = useCartStore((state) => state.cartItems);
    return (_jsx("nav", { className: "bg-white shadow-md", children: _jsx("div", { className: "container mx-auto px-4", children: _jsxs("div", { className: "flex justify-between items-center h-16", children: [_jsx(Link, { to: "/", className: "text-2xl font-bold text-blue-600", children: "EcommerceSaaS" }), _jsxs("div", { className: "hidden md:flex space-x-8", children: [_jsx(Link, { to: "/", className: "text-gray-600 hover:text-gray-900 transition", children: "Products" }), user && user.role === 2 && (_jsx(Link, { to: "/vendor", className: "text-gray-600 hover:text-gray-900 transition", children: "Vendor Dashboard" })), user && user.role === 1 && (_jsx(Link, { to: "/admin", className: "text-gray-600 hover:text-gray-900 transition", children: "Admin Panel" }))] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs(Link, { to: "/cart", className: "relative", children: [_jsx(ShoppingCartIcon, { className: "w-6 h-6 text-gray-600 hover:text-gray-900" }), cartItems.length > 0 && (_jsx("span", { className: "absolute -top-2 -right-2 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center", children: cartItems.length }))] }), user ? (_jsxs("div", { className: "flex items-center space-x-3", children: [_jsxs("div", { className: "flex items-center space-x-2 cursor-pointer", children: [_jsx(UserCircleIcon, { className: "w-6 h-6 text-gray-600" }), _jsx("span", { className: "text-gray-700 text-sm", children: user.firstName })] }), _jsx("button", { onClick: onLogout, className: "px-4 py-2 text-sm text-white bg-red-500 rounded hover:bg-red-600 transition", children: "Logout" })] })) : (_jsxs("div", { className: "flex space-x-2", children: [_jsx("button", { onClick: () => navigate('/login'), className: "px-4 py-2 text-sm text-blue-600 border border-blue-600 rounded hover:bg-blue-50 transition", children: "Login" }), _jsx("button", { onClick: () => navigate('/register'), className: "px-4 py-2 text-sm text-white bg-blue-600 rounded hover:bg-blue-700 transition", children: "Register" })] }))] })] }) }) }));
}
