import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useCartStore } from '@/context/store';
import { Link } from 'react-router-dom';
export default function CartPage() {
    const { cartItems, removeItem, getTotal, clearCart } = useCartStore();
    if (cartItems.length === 0) {
        return (_jsxs("div", { className: "text-center py-12", children: [_jsx("h1", { className: "text-3xl font-bold mb-4", children: "Your Cart is Empty" }), _jsx("p", { className: "text-gray-600 mb-6", children: "Add some products to get started" }), _jsx(Link, { to: "/", className: "inline-block px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition", children: "Continue Shopping" })] }));
    }
    return (_jsxs("div", { className: "py-8", children: [_jsx("h1", { className: "text-3xl font-bold mb-8", children: "Shopping Cart" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8", children: [_jsx("div", { className: "lg:col-span-2", children: _jsx("div", { className: "space-y-4", children: cartItems.map((item) => (_jsxs("div", { className: "bg-white p-4 rounded-lg shadow flex justify-between items-center", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold", children: item.productName }), _jsxs("p", { className: "text-gray-600", children: ["$", item.price.toFixed(2)] })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("span", { className: "text-gray-600", children: ["Qty: ", item.quantity] }), _jsxs("span", { className: "font-semibold", children: ["$", (item.price * item.quantity).toFixed(2)] }), _jsx("button", { onClick: () => removeItem(item.productId), className: "text-red-600 hover:text-red-800 transition", children: "Remove" })] })] }, item.productId))) }) }), _jsxs("div", { className: "bg-white p-6 rounded-lg shadow h-fit", children: [_jsx("h2", { className: "text-lg font-semibold mb-4", children: "Order Summary" }), _jsxs("div", { className: "space-y-2 mb-4", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Subtotal:" }), _jsxs("span", { children: ["$", getTotal().toFixed(2)] })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Shipping:" }), _jsx("span", { children: "$0.00" })] }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "Tax:" }), _jsx("span", { children: "$0.00" })] })] }), _jsx("hr", { className: "my-4" }), _jsxs("div", { className: "flex justify-between font-semibold text-lg mb-6", children: [_jsx("span", { children: "Total:" }), _jsxs("span", { children: ["$", getTotal().toFixed(2)] })] }), _jsx(Link, { to: "/checkout", className: "block w-full text-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition mb-3", children: "Proceed to Checkout" }), _jsx("button", { onClick: () => clearCart(), className: "w-full px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition", children: "Clear Cart" })] })] })] }));
}
